// <auto-generated />
namespace AIUBStudentPortal.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class initdb4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initdb4));
        
        string IMigrationMetadata.Id
        {
            get { return "202505241641032_initdb4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
